service: cloudgto-blog

frameworkVersion: '3'

configValidationMode: error

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  region: us-east-1

appSync: ${file(templates/appsync.yml)}

resources:
  - ${file(templates/dynamodb.yml)}
